-- AlterTable
ALTER TABLE "Media" ADD COLUMN     "userId" TEXT,
ALTER COLUMN "requiredGame" DROP NOT NULL,
ALTER COLUMN "threshold" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "Media" ADD CONSTRAINT "Media_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
